version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: survey
    ports:
      - "5431:5431"
    
  api:
    build: "./server"
    container_name: api-container
    restart: always
    volumes:
      - ./survey:/app
      - ./app:/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - db
    web:
      build: ./survey-front
      container_name: web-container
      ports:
      - "3000:3000"
      stdin_open: true
      tty: true

networks:
  backend:
    driver: "bridge"